spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/offers

offers:
    http:
      client:
        config:
          uri: http://ec2-3-127-218-34.eu-central-1.compute.amazonaws.com
          port: 5057
